# Beyond Pace: Pace-Driven Running vs Navigation-Driven Sports
### *Why Speed Tells Only Part of the Story*

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

C:\Users\viver\AppData\Local\Temp\ipykernel_19064\1850576127.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# завантажуємо датасети

df_personal = pd.read_csv("../data/raw/garmin_personal.csv")
df_partner = pd.read_csv("../data/raw/garmin_partner.csv")
df_activity_bob = pd.read_csv("../data/raw/activity_bob.csv")
df_activity_log = pd.read_csv("../data/raw/activity_log.csv")

### ЗНАЙОМСТВО З ДАНИМИ

In [3]:
# загальна інформація
print("ЗАГАЛЬНА ІНФОРМАЦІЯ ПРО df_personal:")
print()
df_personal.info()

# базова статистика
print()
print("БАЗОВА СТАТИСТИКА ПО df_personal:")
print()
stats = df_personal.describe()
stats.round(2)

ЗАГАЛЬНА ІНФОРМАЦІЯ ПРО df_personal:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Activity Type           307 non-null    object
 1   Date                    307 non-null    object
 2   Favorite                307 non-null    bool
 3   Title                   307 non-null    object
 4   Distance                307 non-null    float64
 5   Calories                307 non-null    object
 6   Time                    307 non-null    object
 7   Avg HR                  307 non-null    int64
 8   Max HR                  307 non-null    int64
 9   Aerobic TE              307 non-null    object
 10  Avg Run Cadence         307 non-null    int64
 11  Max Run Cadence         307 non-null    int64
 12  Avg Pace                307 non-null    object
 13  Best Pace               307 non-null    object
 14  Total Ascent            307 non-null    object
 15  Total Descent           307 non-null    object
 16  Avg Stride Length       307 non-null    float64
 17  Training Stress Score®  307 non-null    float64
 18  Steps                   307 non-null    object
 19  Decompression           307 non-null    object
 20  Best Lap Time           307 non-null    object
 21  Number of Laps          307 non-null    int64
 22  Moving Time             307 non-null    object
 23  Elapsed Time            307 non-null    object
 24  Min Elevation           307 non-null    object
 25  Max Elevation           307 non-null    object
dtypes: bool(1), float64(3), int64(5), object(17)
memory usage: 60.4+ KB

БАЗОВА СТАТИСТИКА ПО df_personal:

,Distance,Avg HR,Max HR,Avg Run Cadence,Max Run Cadence,Avg Stride Length,Training Stress Score®,Number of Laps
count,307.00,307.00,307.00,307.00,307.00,307.00,307.0,307.00
mean,8.03,145.81,175.43,156.89,214.57,0.91,0.0,6.64
std,12.08,18.63,14.95,17.85,32.64,2.65,0.0,13.26
min,0.00,67.00,72.00,104.00,124.00,0.00,0.0,1.00
25%,3.70,140.00,171.00,146.00,186.00,0.56,0.0,1.00
50%,6.91,150.00,179.00,159.00,231.00,0.69,0.0,1.00
75%,9.74,157.50,184.00,173.00,243.00,0.79,0.0,10.00
max,146.35,174.00,204.00,180.00,253.00,38.07,0.0,154.00

In [4]:
df_personal.head()

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Avg Stride Length,Training Stress Score®,Steps,Decompression,Best Lap Time,Number of Laps,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,Trail Running,2026-05-17 11:56:00,False,"🦊3,5 training",8.38,479,01:06:42,151,187,4.0,...,0.76,0.0,"10,334",No,00:01:45.1,11,01:05:22,01:25:19,164,214
1,Trail Running,2026-05-16 14:20:24,False,"🦊3,5 training",9.64,607,01:49:50,139,183,3.1,...,0.61,0.0,"11,556",No,00:01:13.5,13,01:38:19,01:49:50,114,200
2,Trail Running,2026-05-09 11:45:01,False,🦊 144 training,10.90,740,02:31:34,130,175,3.1,...,0.50,0.0,"13,758",No,00:02:56.8,14,01:59:11,02:31:34,121,186
3,Trail Running,2026-05-03 10:16:03,False,Lutskyi raion Running,4.53,299,00:49:57,136,174,2.8,...,0.64,0.0,"5,446",No,00:06:07.4,5,00:43:48,00:49:57,211,250
4,Trail Running,2026-05-02 12:04:59,False,"🦊ARDF, ЧУ 3,5, Луцьк",11.35,617,01:54:51,141,186,3.8,...,0.63,0.0,"12,616",No,00:05:13.9,12,01:33:28,01:54:51,179,218

In [5]:
# загальна інформація
print("ЗАГАЛЬНА ІНФОРМАЦІЯ ПРО df_partner:")
print()
df_partner.info()

# базова статистика
print()
print("БАЗОВА СТАТИСТИКА ПО df_partner:")
print()
stats = df_partner.describe()
stats.round(2)

ЗАГАЛЬНА ІНФОРМАЦІЯ ПРО df_partner:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Activity Type           280 non-null    object
 1   Date                    280 non-null    object
 2   Favorite                280 non-null    bool
 3   Title                   280 non-null    object
 4   Distance                280 non-null    float64
 5   Calories                280 non-null    object
 6   Time                    280 non-null    object
 7   Avg HR                  280 non-null    int64
 8   Max HR                  280 non-null    int64
 9   Avg Run Cadence         280 non-null    object
 10  Max Run Cadence         280 non-null    object
 11  Avg Pace                280 non-null    object
 12  Best Pace               280 non-null    object
 13  Total Ascent            280 non-null    object
 14  Total Descent           280 non-null    object
 15  Avg Stride Length       280 non-null    object
 16  Training Stress Score®  280 non-null    float64
 17  Steps                   280 non-null    object
 18  Decompression           280 non-null    object
 19  Best Lap Time           280 non-null    object
 20  Number of Laps          280 non-null    int64
 21  Moving Time             280 non-null    object
 22  Elapsed Time            280 non-null    object
 23  Min Elevation           280 non-null    object
 24  Max Elevation           280 non-null    object
dtypes: bool(1), float64(2), int64(3), object(19)
memory usage: 52.9+ KB

БАЗОВА СТАТИСТИКА ПО df_partner:

       Distance  Avg HR  Max HR  Training Stress Score®  Number of Laps
count    280.00  280.00  280.00                   280.0          280.00
mean       4.61  148.21  172.04                     0.0            5.24
std        3.40   20.90   23.32                     0.0            3.44
min        0.00   73.00   92.00                     0.0            1.00
25%        1.92  139.00  161.00                     0.0            3.00
50%        4.03  155.00  179.00                     0.0            5.00
75%        6.86  163.00  187.00                     0.0            7.00
max       23.91  175.00  222.00                     0.0           25.00

In [6]:
df_partner.head()

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Avg Run Cadence,...,Avg Stride Length,Training Stress Score®,Steps,Decompression,Best Lap Time,Number of Laps,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,Running,2026-04-19 12:30:22,False,Kyievo-Sviatoshynskyi raion Running,2.60,232,00:25:27,158,181,119,...,0.87,0.0,"3,460",No,00:05:41.6,3,00:22:33,00:25:27,157,190
1,Running,2026-04-19 11:45:37,False,Kyievo-Sviatoshynskyi raion Running,4.96,410,00:41:47,160,180,132,...,0.90,0.0,"6,346",No,00:07:08.9,5,00:36:49,00:41:47,158,191
2,Running,2026-04-18 13:15:35,False,Kyiv Running,2.42,171,00:17:55,159,190,148,...,0.91,0.0,"2,892",No,00:02:21.9,3,00:16:20,00:17:55,124,158
3,Running,2026-04-14 16:56:03,False,Kyievo-Sviatoshynskyi raion Running,1.48,165,00:21:59,140,169,82,...,0.82,0.0,"2,198",No,00:06:54.2,2,00:15:09,00:21:59,176,192
4,Running,2026-04-14 16:05:04,False,Kyievo-Sviatoshynskyi raion Running,3.98,391,00:41:57,157,183,102,...,0.93,0.0,"5,334",No,00:07:55.0,4,00:32:40,00:41:57,158,192

In [7]:
# загальна інформація
print("ЗАГАЛЬНА ІНФОРМАЦІЯ ПРО df_activity_bob:")
print()
df_activity_bob.info()

# базова статистика
print()
print("БАЗОВА СТАТИСТИКА ПО df_activity_bob:")
print()
stats = df_activity_bob.describe()
stats.round(2)

ЗАГАЛЬНА ІНФОРМАЦІЯ ПРО df_activity_bob:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Activity Type             736 non-null    object
 1   Date                      736 non-null    object
 2   Favorite                  736 non-null    bool
 3   Title                     736 non-null    object
 4   Distance                  736 non-null    object
 5   Calories                  736 non-null    object
 6   Time                      736 non-null    object
 7   Avg HR                    736 non-null    object
 8   Max HR                    736 non-null    object
 9   Aerobic TE                736 non-null    object
 10  Avg Run Cadence           736 non-null    object
 11  Max Run Cadence           736 non-null    object
 12  Avg Pace                  736 non-null    object
 13  Best Pace                 736 non-null    object
 14  Total Ascent              736 non-null    object
 15  Total Descent             736 non-null    object
 16  Avg Stride Length         736 non-null    object
 17  Avg Vertical Ratio        736 non-null    object
 18  Avg Vertical Oscillation  736 non-null    object
 19  Avg Ground Contact Time   736 non-null    object
 20  Avg GAP                   736 non-null    object
 21  Normalized Power® (NP®)   736 non-null    object
 22  Training Stress Score®    736 non-null    object
 23  Avg Power                 736 non-null    object
 24  Max Power                 736 non-null    object
 25  Grit                      736 non-null    object
 26  Flow                      736 non-null    object
 27  Total Strokes             736 non-null    object
 28  Avg. Swolf                736 non-null    object
 29  Avg Stroke Rate           736 non-null    object
 30  Steps                     736 non-null    object
 31  Body Battery Drain        736 non-null    object
 32  Min Temp                  736 non-null    object
 33  Decompression             736 non-null    object
 34  Best Lap Time             736 non-null    object
 35  Number of Laps            736 non-null    object
 36  Max Temp                  736 non-null    object
 37  Moving Time               736 non-null    object
 38  Elapsed Time              736 non-null    object
 39  Min Elevation             736 non-null    object
 40  Max Elevation             736 non-null    object
dtypes: bool(1), object(40)
memory usage: 230.8+ KB

БАЗОВА СТАТИСТИКА ПО df_activity_bob:

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Body Battery Drain,Min Temp,Decompression,Best Lap Time,Number of Laps,Max Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation
count,736,736,736,736,736,736,736,736,736,736,...,736,736,736,736,736,736,736,736,736,736
unique,10,733,2,42,508,506,698,69,87,47,...,36,27,1,173,35,27,310,377,79,91
top,Running,2015-11-23 08:06:20,False,Untitled,"10,00",--,01:15:00,--,--,--,...,--,--,No,--:--:--,--,--,--:--:--,00:NaN:NaN,--,--
freq,523,2,729,251,8,82,5,397,397,479,...,602,692,736,490,403,687,425,351,296,296

In [8]:
df_activity_bob.head()

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Body Battery Drain,Min Temp,Decompression,Best Lap Time,Number of Laps,Max Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,Running,2026-05-19 07:15:28,False,Vyshhorodskyi raion - Пороговое значен,"10,32",663,02:02:14,103,156,"2,7",...,-23,--,No,00:02:00,6,--,02:01:22,02:02:14,119,134
1,Running,2026-05-16 10:30:56,False,Vyshhorodskyi raion - Длит. проб.,"11,26",781,02:13:34,112,190,"3,3",...,-32,--,No,01:05:34,2,--,02:10:30,02:13:34,116,133
2,Running,2026-05-10 08:18:24,False,Vyshhorodskyi raion - База,"10,32",734,01:47:45,153,182,"3,1",...,-26,--,No,00:27:00,2,--,01:46:54,01:47:45,118,134
3,Running,2026-05-09 06:22:41,False,Vyshhorodskyi raion - База,"10,73",722,01:55:54,142,158,"3,0",...,-25,--,No,00:40:00,2,--,01:54:55,01:55:54,118,133
4,Running,2026-05-07 06:00:01,False,Vyshhorodskyi raion - Пороговое значен,"9,67",644,01:44:42,103,175,"2,9",...,-18,--,No,00:02:00,6,--,01:42:26,01:44:42,118,133

In [9]:
# загальна інформація
print("ЗАГАЛЬНА ІНФОРМАЦІЯ ПРО df_activity_log:")
print()
df_activity_log.info()

# базова статистика
print()
print("БАЗОВА СТАТИСТИКА ПО df_activity_log:")
print()
stats = df_activity_log.describe()
stats.round(2)

ЗАГАЛЬНА ІНФОРМАЦІЯ ПРО df_activity_log:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Activity Type      689 non-null    object
 1   Date               689 non-null    object
 2   Title              689 non-null    object
 3   Distance           689 non-null    float64
 4   Calories           689 non-null    object
 5   Time               689 non-null    object
 6   Avg HR             689 non-null    object
 7   Max HR             689 non-null    object
 8   Avg Run Cadence    689 non-null    object
 9   Max Run Cadence    689 non-null    object
 10  Avg Pace           689 non-null    object
 11  Best Pace          689 non-null    object
 12  Elev Gain          689 non-null    object
 13  Elev Loss          689 non-null    object
 14  Avg Stride Length  689 non-null    float64
 15  Best Lap Time      689 non-null    object
 16  Number of Laps     689 non-null    int64
dtypes: float64(2), int64(1), object(14)
memory usage: 91.6+ KB

БАЗОВА СТАТИСТИКА ПО df_activity_log:

       Distance  Avg Stride Length  Number of Laps
count    689.00             689.00          689.00
mean       5.16               1.28            5.58
std        3.94               0.34            4.01
min        0.00               0.00            1.00
25%        2.07               1.23            2.00
50%        4.03               1.29            5.00
75%        7.96               1.36            8.00
max       18.01               1.86           19.00

___

### ПОРІВНЯННЯ КОЛОНОК ДАТАФРЕЙМІВ

In [10]:
# зручний вивід для наочного порівняння:

df = pd.DataFrame({
    "garmin_personal": pd.Series(df_personal.columns.tolist()),
    "garmin_partner": pd.Series(df_partner.columns.tolist()),
    "activity_bob": pd.Series(df_activity_bob.columns.tolist()),
    "activity_log": pd.Series(df_activity_log.columns.tolist())
})
df

,garmin_personal,garmin_partner,activity_bob,activity_log
0,Activity Type,Activity Type,Activity Type,Activity Type
1,Date,Date,Date,Date
2,Favorite,Favorite,Favorite,Title
3,Title,Title,Title,Distance
4,Distance,Distance,Distance,Calories
5,Calories,Calories,Calories,Time
6,Time,Time,Time,Avg HR
7,Avg HR,Avg HR,Avg HR,Max HR
8,Max HR,Max HR,Max HR,Avg Run Cadence
9,Aerobic TE,Avg Run Cadence,Aerobic TE,Max Run Cadence
10,Avg Run Cadence,Max Run Cadence,Avg Run Cadence,Avg Pace
11,Max Run Cadence,Avg Pace,Max Run Cadence,Best Pace
12,Avg Pace,Best Pace,Avg Pace,Elev Gain
13,Best Pace,Total Ascent,Best Pace,Elev Loss
14,Total Ascent,Total Descent,Total Ascent,Avg Stride Length
15,Total Descent,Avg Stride Length,Total Descent,Best Lap Time
16,Avg Stride Length,Training Stress Score®,Avg Stride Length,Number of Laps
17,Training Stress Score®,Steps,Avg Vertical Ratio,NaN
18,Steps,Decompression,Avg Vertical Oscillation,NaN
19,Decompression,Best Lap Time,Avg Ground Contact Time,NaN
20,Best Lap Time,Number of Laps,Avg GAP,NaN
21,Number of Laps,Moving Time,Normalized Power® (NP®),NaN
22,Moving Time,Elapsed Time,Training Stress Score®,NaN
23,Elapsed Time,Min Elevation,Avg Power,NaN
24,Min Elevation,Max Elevation,Max Power,NaN
25,Max Elevation,NaN,Grit,NaN
26,NaN,NaN,Flow,NaN
27,NaN,NaN,Total Strokes,NaN
28,NaN,NaN,Avg. Swolf,NaN
29,NaN,NaN,Avg Stroke Rate,NaN
30,NaN,NaN,Steps,NaN
31,NaN,NaN,Body Battery Drain,NaN
32,NaN,NaN,Min Temp,NaN
33,NaN,NaN,Decompression,NaN
34,NaN,NaN,Best Lap Time,NaN
35,NaN,NaN,Number of Laps,NaN
36,NaN,NaN,Max Temp,NaN
37,NaN,NaN,Moving Time,NaN
38,NaN,NaN,Elapsed Time,NaN
39,NaN,NaN,Min Elevation,NaN
40,NaN,NaN,Max Elevation,NaN

___

### АНАЛІЗ ПРОПУЩЕНИХ ЗНАЧЕНЬ

In [11]:
# Аналіз пропущених значень

for name, df in [
    ("garmin_personal", df_personal),
    ("garmin_partner", df_partner),
    ("activity_bob", df_activity_bob),
    ("activity_log", df_activity_log)
]:
    missing = df.isnull().sum()
    missing_percent = (missing / len(df) * 100).round(1)
    print(f"\n{name}")
    print(missing_percent[missing_percent > 0])

garmin_personal
Series([], dtype: float64)

garmin_partner
Series([], dtype: float64)

activity_bob
Series([], dtype: float64)

activity_log
Series([], dtype: float64)

___

### CLEANING

#### Одразу позбудемось пропущених значень:

In [12]:
df_personal = df_personal.replace('--', None)
df_partner = df_partner.replace('--', None)
df_activity_bob = df_activity_bob.replace('--', None)
df_activity_log = df_activity_log.replace('--', None)

####  Залишаємо тільки потрібні типи активностей:

In [13]:
keep_types = ["Running", "Trail Running", "Treadmill Running", "Indoor Running", "Other"]

df_personal = df_personal[df_personal["Activity Type"].isin(keep_types)]
df_partner = df_partner[df_partner["Activity Type"].isin(keep_types)]
df_activity_bob = df_activity_bob[df_activity_bob["Activity Type"].isin(keep_types)]
df_activity_log = df_activity_log[df_activity_log["Activity Type"].isin(keep_types)]

___
#### Перевіримо на наявність аномалій:

In [14]:
df_personal[["Distance", "Time"]].head(10)

   Distance      Time
0      8.38  01:06:42
1      9.64  01:49:50
2     10.90  02:31:34
3      4.53  00:49:57
4     11.35  01:54:51
5     11.10  01:39:03
6      2.91  00:27:01
7      2.66  00:21:22
8      7.81  01:19:37
9     10.60  00:59:29

In [15]:
# конвертуємо час

df_personal["Time_hours"] = pd.to_timedelta(df_personal["Time"]).dt.total_seconds() / 3600
df_personal["speed_kmh"] = df_personal["Distance"] / df_personal["Time_hours"]

In [16]:
df_personal[["Distance", "Time", "Time_hours", "speed_kmh"]].head(10)

   Distance      Time  Time_hours  speed_kmh
0      8.38  01:06:42    1.111667   7.538231
1      9.64  01:49:50    1.830556   5.266161
2     10.90  02:31:34    2.526111   4.314933
3      4.53  00:49:57    0.832500   5.441441
4     11.35  01:54:51    1.914167   5.929473
5     11.10  01:39:03    1.650833   6.723877
6      2.91  00:27:01    0.450278   6.462677
7      2.66  00:21:22    0.356111   7.469579
8      7.81  01:19:37    1.326944   5.885702
9     10.60  00:59:29    0.991389  10.692071

In [17]:
df_personal[df_personal["speed_kmh"] > 20]

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Steps,Decompression,Best Lap Time,Number of Laps,Moving Time,Elapsed Time,Min Elevation,Max Elevation,Time_hours,speed_kmh
17,Trail Running,2026-04-03 06:41:08,False,🤣🦊ARDF 144 ЧУ Вінниця - running during an air ...,94.51,630,02:01:19,142,184,3.1,...,"12,406",No,00:00:12.5,95,01:54:07,02:01:19,108,998,2.021944,46.742135
18,Running,2026-04-02 11:57:27,False,Vinnytsia - running during an air raid,111.04,248,00:38:22,152,183,3.7,...,"4,764",No,00:00:16.6,111,00:37:54,00:38:22,102,"1,090",0.639444,173.650738
28,Trail Running,2026-02-28 04:12:08,False,running during an air raid,30.57,47,00:09:05.8,146,169,2.3,...,700,No,00:00:08.9,31,00:08:46.5,00:09:05.8,104,176,0.151611,201.634298
53,Trail Running,2025-10-04 14:40:02,False,Kyiv - running during an air raid,146.35,355,00:53:20,165,183,5.0,...,"7,064",No,00:00:00.3,154,00:52:35,00:53:20,4,"1,185",0.888889,164.643750

Отримали перелік аномальних пробіжок.

Це наслідок GPS-аномалій від роботи ППО при повітряних тривогах (Україна, 2026).

Оскільки df_partner відображає тренування в цих же воєнних реаліях, його теж слід перевірити на наявність таких викидів:

In [18]:
df_partner["Time_hours"] = pd.to_timedelta(df_partner["Time"]).dt.total_seconds() / 3600
df_partner["speed_kmh"] = df_partner["Distance"] / df_partner["Time_hours"]


df_partner[["Distance", "Time", "Time_hours", "speed_kmh"]].head(10)

   Distance      Time  Time_hours  speed_kmh
0      2.60  00:25:27    0.424167   6.129666
1      4.96  00:41:47    0.696389   7.122457
2      2.42  00:17:55    0.298611   8.104186
3      1.48  00:21:59    0.366389   4.039424
4      3.98  00:41:57    0.699167   5.692491
5      7.92  01:06:24    1.106667   7.156627
6      3.02  00:27:40    0.461111   6.549398
7      6.62  01:00:35    1.009722   6.556259
8      5.86  00:48:14    0.803889   7.289565
9      7.12  00:55:27    0.924167   7.704238

In [19]:
df_partner[df_partner["speed_kmh"] > 20]

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Avg Run Cadence,...,Steps,Decompression,Best Lap Time,Number of Laps,Moving Time,Elapsed Time,Min Elevation,Max Elevation,Time_hours,speed_kmh
46,Running,2025-09-02 02:15:38,False,Rimac Running,23.00,476,00:57:37,150,180,116,...,"7,780",No,00:00:00.8,25,00:26:29,00:57:37,None,988,0.960278,23.951403
49,Running,2025-08-30 08:11:55,False,Lima Running,23.91,459,00:50:25,158,182,104,...,"6,438",No,00:00:17.0,24,00:37:56,00:50:25,100,987,0.840278,28.454876

На першщий погляд ці записи є нормальними швидкісними забігами.

Їх аномальний характер легко пропустити навіть зараз. Їх дивну природу слід додатково обгрунтувати і критерій швидкості руху виявляється недостатнім.

Врятувало таке спостереження - під час повітряних тривог GPS не працює і ламає Distance, але інші фізичні параметри годинник продовжує зчитувати сумлінно. Таким чином у нас лишається параметр Steps який правдиво відображає довжину пробіжки!

Тому в якості критерія перевірки пробіжки на аномальність слід використати steps_per_km на додачу до speed_kmh

In [20]:
df_personal["Steps"] = df_personal["Steps"].str.replace(",", "").astype(int)

In [21]:
df_personal["steps_per_km"] = df_personal["Steps"] / df_personal["Distance"]

In [22]:
# Визначимо нормальний діапазон steps_per_km для df_personal

personal_normal_steps_per_km = df_personal[
    (df_personal["Steps"].notna()) & 
    (df_personal["Distance"] > 0) &
    (df_personal["speed_kmh"] <= 20)  # виключаємо підозрілі записи
]["steps_per_km"].describe()

print(personal_normal_steps_per_km)

count     285.000000
mean     1218.620647
std       621.628283
min        23.497997
25%      1098.003630
50%      1202.207506
75%      1291.559086
max      9546.875000
Name: steps_per_km, dtype: float64

Аномальними ввжаємо записи, в яких speed_kmh > 20 та steps_per_km нижче нормального діапазону

Нормальний діапазон personal_normal_steps_per_km: 1088-1305 кроків/км

Записи де 131 чи 22 кроків/км — в 7-9 разів нижче норми - це явна GPS-аномалія.

In [23]:
# Нормальний діапазон: 1088-1305 кроків/км
# умовно, записи де < 500 кроків/км визнаємо GPS-аномаліями

anomalies_personal = df_personal[
    (df_personal["speed_kmh"] > 20) & 
    (df_personal["steps_per_km"] < 500)
]
anomalies_personal[["Title", "Distance", "Steps", "speed_kmh", "steps_per_km"]]

,Title,Distance,Steps,speed_kmh,steps_per_km
17,🤣🦊ARDF 144 ЧУ Вінниця - running during an air ...,94.51,12406,46.742135,131.266533
18,Vinnytsia - running during an air raid,111.04,4764,173.650738,42.903458
28,running during an air raid,30.57,700,201.634298,22.898266
53,Kyiv - running during an air raid,146.35,7064,164.643750,48.267851

повторюємо ці кроки для df_partner

In [24]:
df_partner["Steps"] = df_partner["Steps"].str.replace(",", "").replace("--", None).astype(float)

In [25]:
df_partner["steps_per_km"] = df_partner["Steps"] / df_partner["Distance"]

In [26]:
normal_steps_per_km = df_partner[
    (df_partner["Steps"].notna()) & 
    (df_partner["Distance"] > 0) &
    (df_partner["speed_kmh"] <= 20)  # виключаємо підозрілі записи
]["steps_per_km"].describe()

print(normal_steps_per_km)

count     274.000000
mean     1222.241413
std       177.371730
min       290.082645
25%      1150.874083
50%      1211.494316
75%      1310.413372
max      2062.365591
Name: steps_per_km, dtype: float64

In [27]:
# Нормальний діапазон: 1150-1310 кроків/км
# умовно, записи де < 500 кроків/км визнаємо GPS-аномаліями

anomalies_partner = df_partner[
    (df_partner["speed_kmh"] > 20) & 
    (df_partner["steps_per_km"] < 500)
]
anomalies_partner[["Title", "Distance", "Steps", "speed_kmh", "steps_per_km"]]

            Title  Distance   Steps  speed_kmh  steps_per_km
46  Rimac Running     23.00  7780.0  23.951403    338.260870
49   Lima Running     23.91  6438.0  28.454876    269.259724

Отже, ми нарешті довели аномальну природу деяких записів із 2 датасетів.

Видаляємо їх:

In [28]:
# пастка з хардкодингом індексів, шукаємо інший шлях

# df_personal = df_personal.drop([15, 16, 26, 51])

# df_partner = df_partner.drop([46, 49])

In [29]:
# "~" використаємо фільтр = "НЕ" = залишаємо все що не є аномалією
# та .index.isin() — чиї індекси є в списку аномалій

df_personal = df_personal[~df_personal.index.isin(anomalies_personal.index)]

df_partner = df_partner[~df_partner.index.isin(anomalies_partner.index)]

In [30]:
# перевіримо чи видалились

print(df_personal.shape)
print(df_partner.shape)

(295, 29)
(276, 28)

##### Перевіримо також і інші 2 датасети:

In [31]:
df_activity_bob[["Distance", "Time"]].head(10)

  Distance      Time
0    10,32  02:02:14
1    11,26  02:13:34
2    10,32  01:47:45
3    10,73  01:55:54
4     9,67  01:44:42
5     9,41  01:46:46
6     9,42  01:44:32
7     9,41  01:43:26
8     9,45  01:43:53
9     9,46  01:40:30

In [32]:
# треба конвертувати Distance - заважає розділювач кома:

df_activity_bob["Distance"] = df_activity_bob["Distance"].str.replace(',', '.').astype(float)

In [33]:
df_activity_bob["Time_hours"] = pd.to_timedelta(df_activity_bob["Time"]).dt.total_seconds() / 3600
df_activity_bob["speed_kmh"] = df_activity_bob["Distance"] / df_activity_bob["Time_hours"]


df_activity_bob[["Distance", "Time", "Time_hours", "speed_kmh"]].head(10)

   Distance      Time  Time_hours  speed_kmh
0     10.32  02:02:14    2.037222   5.065721
1     11.26  02:13:34    2.226111   5.058148
2     10.32  01:47:45    1.795833   5.746636
3     10.73  01:55:54    1.931667   5.554789
4      9.67  01:44:42    1.745000   5.541547
5      9.41  01:46:46    1.779444   5.288167
6      9.42  01:44:32    1.742222   5.406888
7      9.41  01:43:26    1.723889   5.458588
8      9.45  01:43:53    1.731389   5.458046
9      9.46  01:40:30    1.675000   5.647761

In [34]:
df_activity_bob[["Distance", "Time"]].head(10)

   Distance      Time
0     10.32  02:02:14
1     11.26  02:13:34
2     10.32  01:47:45
3     10.73  01:55:54
4      9.67  01:44:42
5      9.41  01:46:46
6      9.42  01:44:32
7      9.41  01:43:26
8      9.45  01:43:53
9      9.46  01:40:30

In [35]:
print(df_activity_bob.shape)
print(df_activity_bob.dtypes)

(625, 43)
Activity Type                object
Date                         object
Favorite                       bool
Title                        object
Distance                    float64
Calories                     object
Time                         object
Avg HR                       object
Max HR                       object
Aerobic TE                   object
Avg Run Cadence              object
Max Run Cadence              object
Avg Pace                     object
Best Pace                    object
Total Ascent                 object
Total Descent                object
Avg Stride Length            object
Avg Vertical Ratio           object
Avg Vertical Oscillation     object
Avg Ground Contact Time      object
Avg GAP                      object
Normalized Power® (NP®)      object
Training Stress Score®       object
Avg Power                    object
Max Power                    object
Grit                         object
Flow                         object
Total Strokes                object
Avg. Swolf                   object
Avg Stroke Rate              object
Steps                        object
Body Battery Drain           object
Min Temp                     object
Decompression                object
Best Lap Time                object
Number of Laps               object
Max Temp                     object
Moving Time                  object
Elapsed Time                 object
Min Elevation                object
Max Elevation                object
Time_hours                  float64
speed_kmh                   float64
dtype: object

In [36]:
df_activity_bob[df_activity_bob["speed_kmh"] > 20]

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Decompression,Best Lap Time,Number of Laps,Max Temp,Moving Time,Elapsed Time,Min Elevation,Max Elevation,Time_hours,speed_kmh
64,Running,2025-10-04 06:30:19,False,San Martín de Porres - База,46.65,289,00:46:26,126,162,"2,0",...,No,"00:06:25,8",2,None,00:39:39,00:46:26,177,214,0.773889,60.279971
735,Running,2011-01-28 08:25:25,False,Без названия,34.56,1.126,00:49:58,None,None,None,...,No,--:--:--,None,None,--:--:--,00:NaN:NaN,None,None,0.832778,41.499666

In [37]:
# всі нечислові значення обробимо errors='coerce':

df_activity_bob["Steps"] = pd.to_numeric(
    df_activity_bob["Steps"].astype(str).str.replace('.', '', regex=False), 
    errors='coerce'
)

In [38]:
df_activity_bob["Steps"] = df_activity_bob["Steps"].astype(str).str.replace('.', '', regex=False).astype(float)

In [39]:
df_activity_bob["Steps"].head()

0    174520.0
1    182860.0
2    161400.0
3    171260.0
4    151920.0
Name: Steps, dtype: float64

In [40]:
df_activity_bob["steps_per_km"] = df_activity_bob["Steps"] / df_activity_bob["Distance"]

In [41]:
# Визначимо нормальний діапазон steps_per_km для df_personal

activity_bob_normal_steps_per_km = df_activity_bob[
    (df_activity_bob["Steps"].notna()) & 
    (df_activity_bob["Distance"] > 0) &
    (df_activity_bob["speed_kmh"] <= 20)  # виключаємо підозрілі записи
]["steps_per_km"].describe()

print(activity_bob_normal_steps_per_km)

count      240.000000
mean     13829.825021
std       3126.711968
min        121.524202
25%      12814.009969
50%      14423.263604
75%      15602.309207
max      30398.081535
Name: steps_per_km, dtype: float64

In [42]:
df_activity_bob[["Distance", "Steps", "steps_per_km"]].dropna().head(10)

   Distance     Steps  steps_per_km
0     10.32  174520.0  16910.852713
1     11.26  182860.0  16239.786856
2     10.32  161400.0  15639.534884
3     10.73  171260.0  15960.857409
4      9.67  151920.0  15710.444674
5      9.41  152740.0  16231.668438
6      9.42  151820.0  16116.772824
7      9.41  150720.0  16017.003188
8      9.45  148180.0  15680.423280
9      9.46  147540.0  15596.194503

In [43]:
# Нормальний діапазон: 1039-1546 кроків/км
# умовно, записи де < 500 кроків/км визнаємо GPS-аномаліями

anomalies_activity_bob = df_activity_bob[
    (df_activity_bob["speed_kmh"] > 20) & 
    (df_activity_bob["steps_per_km"] < 500)
]
anomalies_activity_bob[["Title", "Distance", "Steps", "speed_kmh", "steps_per_km"]]

Empty DataFrame
Columns: [Title, Distance, Steps, speed_kmh, steps_per_km]
Index: []

In [44]:
df_activity_bob.loc[735, ["Title", "Distance", "Steps", "speed_kmh", "steps_per_km", "Best Pace"]]

Title           Без названия
Distance               34.56
Steps                    NaN
speed_kmh          41.499666
steps_per_km             NaN
Best Pace               0:02
Name: 735, dtype: object

Отже, ми виявили аномальні записи, один з них 2025 року - знов маємо фактор війни, інший -навпаки, 2011 рік, найперший запис в датасеті, мабуть тестовий, абсолютно нереалістичний (Best Pace = 0:02, NaN в більшості полів) - тому його теж видаляємо, вручну.

Видаляємо їх:

In [45]:
df_activity_bob = df_activity_bob[~df_activity_bob.index.isin(anomalies_activity_bob.index)]
df_activity_bob = df_activity_bob.drop(735)

І перевірка останнього датафрейму:

In [46]:
df_activity_log[["Distance", "Time"]].head(10)

   Distance     Time
0      6.00  0:43:55
1      6.50  0:47:04
2      5.01  0:40:29
3      7.01  0:52:55
4      5.19  0:41:35
5      6.51  0:45:48
6      5.01  0:35:11
7      5.00  0:35:29
8      6.00  0:42:31
9      3.11  0:25:04

In [47]:
df_activity_log["Time"].unique()

array(['0:43:55', '0:47:04', '0:40:29', '0:52:55', '0:41:35', '0:45:48',
       '0:35:11', '0:35:29', '0:42:31', '0:25:04', '0:44:49', '0:35:12',
       '0:32:16', '0:39:49', '0:52:45', '0:44:06', '0:49:03', '0:39:06',
       '0:50:05', '0:47:07', '0:37:47', '0:41:23', '0:34:04', '0:39:47',
       '0:50:04', '0:42:33', '0:33:39', '1:02:25', '0:39:45', '0:50:54',
       '0:40:37', '0:32:08', '1:01:19', '0:38:25', '0:38:15', '0:38:52',
       '0:44:23', '0:42:05', '0:29:02', '0:48:04', '0:48:03', '0:36:25',
       '0:42:22', '0:43:20', '0:29:06', '0:25:37', '0:40:47', '0:45:27',
       '0:44:03', '0:23:55', '0:20:56', '0:47:36', '0:37:45', '0:45:50',
       '0:30:22', '0:24:32', '0:36:45', '0:37:57', '0:39:23', '0:40:40',
       '0:37:39', '0:36:32', '0:52:52', '0:31:25', '0:44:42', '0:24:30',
       '0:22:16', '0:30:44', '0:22:59', '0:36:46', '0:46:31', '0:23:14',
       '0:25:19', '0:31:37', '0:33:54', '0:42:58', '0:28:10', '0:32:46',
       '0:29:25', '0:22:18', '0:36:24', '0:15:41', '0:23:49', '0:23:24',
       '0:15:45', '0:26:33', '09:18.1', '0:29:14', '0:22:06', '0:21:53',
       '0:43:26', '0:39:57', '0:24:12', '0:36:54', '0:28:24', '0:23:00',
       '0:17:04', '0:28:50', '0:17:34', '0:27:07', '0:28:33', '0:35:14',
       '0:21:06', '0:22:54', '0:22:05', '0:35:33', '0:36:00', '0:37:20',
       '0:29:32', '0:25:47', '0:28:56', '0:26:20', '0:28:31', '0:29:10',
       '0:29:53', '0:15:09', '0:35:56', '05:57.7', '07:51.0', '0:19:55',
       '0:27:12', '0:28:46', '0:23:18', '0:48:42', '0:41:12', '0:46:15',
       '0:21:40', '0:37:56', '0:46:59', '0:27:26', '0:30:34', '0:52:14',
       '0:37:30', '0:45:24', '0:30:11', '0:43:30', '0:36:02', '0:28:00',
       '0:28:32', '0:30:53', '0:32:58', '0:31:30', '0:13:43', '0:14:28',
       '0:39:05', '0:17:50', '0:15:18', '0:32:02', '0:49:59', '1:00:46',
       '0:27:59', '06:31.1', '05:14.4', '05:14.8', '0:13:53', '1:06:14',
       '1:34:29', '1:07:33', '0:29:04', '0:15:48', '1:21:00', '09:38.8',
       '04:44.6', '0:27:28', '0:13:35', '0:27:38', '1:07:13', '0:52:51',
       '0:04:10', '0:33:09', '0:17:39', '0:50:35', '0:31:13', '0:12:23',
       '0:14:32', '1:02:00', '1:03:00', '1:02:28', '1:51:34', '0:31:38',
       '0:16:51', '0:16:54', '0:14:15', '0:49:11', '1:07:56', '0:27:42',
       '1:08:24', '0:27:37', '06:08.2', '0:19:16', '0:13:45', '0:29:07',
       '0:49:55', '1:52:31', '1:08:46', '1:08:53', '0:27:47', '1:20:19',
       '0:15:50', '07:09.5', '04:30.6', '02:59.2', '02:58.2', '02:58.0',
       '02:57.2', '02:58.1', '02:54.1', '0:14:13', '1:10:04', '1:57:51',
       '1:12:37', '0:15:16', '0:15:23', '0:14:52', '0:23:15', '1:09:59',
       '0:22:38', '0:23:38', '0:14:08', '0:28:30', '1:07:08', '1:59:19',
       '1:09:40', '1:13:03', '1:22:41', '0:52:37', '0:09:30', '0:53:44',
       '1:56:42', '1:11:48', '1:09:08', '0:14:50', '0:30:05', '0:19:00',
       '0:21:05', '1:10:28', '0:22:12', '07:31.0', '0:10:03', '0:10:05',
       '0:13:52', '1:01:33', '1:58:32', '1:10:07', '0:32:21', '0:28:58',
       '0:56:07', '0:16:12', '0:27:51', '1:10:02', '1:48:57', '1:16:03',
       '0:25:36', '0:13:58', '0:27:27', '1:02:19', '0:16:00', '0:27:48',
       '0:23:39', '1:08:34', '1:52:08', '0:15:36', '0:26:43', '0:14:29',
       '0:46:00', '1:07:14', '1:12:05', '0:28:51', '0:18:13', '0:13:44',
       '1:34:00', '1:05:01', '1:11:27', '0:30:17', '0:23:10', '0:13:47',
       '1:18:09', '0:24:47', '0:22:37', '0:14:26', '02:07.2', '0:22:52',
       '1:12:35', '1:43:30', '1:09:57', '0:25:14', '0:17:25', '1:00:20',
       '0:20:31', '1:18:54', '0:17:37', '0:18:50', '1:13:57', '1:45:34',
       '0:34:14', '0:11:55', '0:19:57', '0:33:57', '03:46.9', '03:41.0',
       '03:41.9', '03:45.3', '03:48.3', '03:50.0', '0:14:36', '1:11:26',
       '1:41:57', '1:13:52', '0:15:40', '0:17:44', '0:49:35', '1:16:18',
       '0:27:09', '07:16.7', '0:15:34', '00:00.2', '1:09:26', '1:34:50',
       '1:09:49', '01:08.6', '01:10.6', '01:06.9', '01:07.6', '03:46.3',
       '03:47.4', '02:25.5', '02:24.9', '02:23.0', '0:14:46', '0:53:52',
       '1:05:14', '0:17:21', '06:22.6', '06:32.3', '06:32.8', '06:32.1',
       '0:14:06', '1:01:46', '0:14:45', '1:35:11', '0:19:58', '0:16:16',
       '0:17:35', '0:52:26', '0:28:14', '0:18:31', '0:14:04', '0:56:30',
       '0:10:47', '0:25:35', '0:14:23', '1:01:28', '1:29:15', '0:56:00',
       '0:16:17', '0:22:17', '0:53:33', '0:57:47', '0:47:37', '0:53:51',
       '0:58:23', '0:57:44', '0:37:54', '0:36:41', '0:55:10', '09:47.8',
       '01:50.2', '01:47.8', '01:47.7', '02:31.5', '02:26.0', '02:25.7',
       '02:24.5', '02:24.4', '05:09.4', '0:13:57', '1:00:41', '1:26:31',
       '0:13:36', '0:16:03', '0:14:51', '0:10:37', '0:47:12', '0:52:08',
       '0:14:22', '0:14:03', '1:42:02', '0:51:39', '0:10:33', '06:31.3',
       '06:32.2', '06:29.4', '0:12:43', '0:48:51', '1:18:46', '0:47:24',
       '0:36:38', '0:21:15', '05:00.5', '05:00.1', '05:00.8', '1:21:47',
       '0:12:25', '0:15:15', '0:36:33', '0:59:38', '0:35:49', '0:18:19',
       '03:11.6', '06:26.5', '03:13.8', '06:26.7', '03:14.6', '03:07.6',
       '0:21:00', '0:59:36', '1:23:25', '0:51:03', '0:17:06', '01:10.4',
       '01:13.4', '01:12.0', '01:14.4', '0:21:29', '0:17:03', '0:56:58',
       '0:51:43', '0:20:05', '02:57.1', '04:44.7', '04:41.9', '03:04.3',
       '04:43.1', '03:02.2', '03:03.7', '0:19:27', '1:09:25', '1:24:03',
       '0:26:36', '0:11:39', '0:15:21', '0:36:08', '1:14:06', '1:06:00',
       '0:21:54', '07:02.6', '06:54.7', '06:52.2', '0:16:23', '1:07:45',
       '1:44:20', '0:50:25', '0:12:27', '04:42.9', '04:47.9', '04:55.0',
       '05:04.2', '05:09.9', '05:18.0', '0:14:02', '1:14:45', '0:53:42',
       '0:15:02', '04:54.0', '05:22.6', '01:49.0', '01:48.7', '01:47.3',
       '01:49.4', '01:51.4', '01:47.4', '1:13:50', '1:57:00', '0:26:18',
       '0:15:27', '0:14:00', '0:40:35', '1:16:20', '0:14:48', '0:39:15',
       '0:16:02', '05:18.3', '05:20.9', '05:16.2', '05:09.0', '05:04.4',
       '0:16:32', '1:03:48', '1:53:00', '0:47:00', '0:45:28', '1:06:41',
       '0:49:56', '0:10:23', '03:24.8', '05:20.2', '08:10.1', '07:49.2',
       '09:34.3', '1:02:55', '1:53:37', '1:12:58', '0:15:08', '0:29:36',
       '1:08:22', '1:07:53', '1:08:35', '1:56:07', '0:50:00', '1:12:10',
       '1:19:03', '0:23:53', '05:30.8', '02:43.1', '02:44.0', '0:18:38',
       '0:17:11', '0:24:57', '1:56:08', '08:01.6', '1:09:22', '0:30:37',
       '1:05:12', '0:31:53', '0:24:40', '09:39.3', '0:14:05', '1:10:40',
       '1:54:54', '0:19:56', '03:37.8', '1:17:47', '0:17:00', '0:28:36',
       '1:07:50', '1:16:52', '0:17:12', '0:13:13', '0:12:50', '0:19:31',
       '1:08:39', '1:58:59', '0:35:32', '0:12:04', '0:35:01', '0:16:55',
       '0:55:44', '1:08:57', '1:18:37', '1:08:37', '2:00:00', '0:22:00',
       '1:05:49', '1:18:34', '0:38:39', '0:36:49', '1:21:07', '1:26:07',
       '1:07:34', '0:56:47', '1:08:06', '0:53:19', '0:20:38', '1:09:53',
       '1:18:17', '1:04:58', '0:29:56', '1:11:42', '1:24:42', '0:20:51',
       '1:12:16', '0:12:58', '0:57:13', '02:12.7', '1:55:37', '0:21:11',
       '0:56:41', '1:15:24', '0:34:28', '0:10:31', '05:15.2', '0:18:02',
       '0:28:23', '1:16:12', '1:48:00', '1:17:00', '0:58:00', '0:59:25',
       '0:15:24', '0:15:53', '0:56:32', '0:41:09', '0:10:42', '02:21.8',
       '0:16:42', '1:19:06', '1:40:56', '1:12:50', '0:46:01', '0:14:37',
       '0:57:40', '1:16:41', '0:38:43', '05:22.2', '05:23.4', '0:21:24',
       '1:04:41', '1:34:27', '1:04:06', '1:03:23', '1:14:59', '1:04:35',
       '0:23:07', '1:06:20', '1:09:24', '1:25:12', '0:15:30', '0:54:36',
       '1:03:08', '1:05:39', '1:14:10', '0:54:10', '0:57:26', '0:58:17',
       '1:00:38', '0:51:56', '0:44:33', '0:47:56', '0:49:18', '0:46:07',
       '0:36:47', '0:42:19', '0:55:33', '0:42:24', '0:45:17', '0:30:28'],
      dtype=object)

In [48]:
df_activity_log["Time_hours"] = pd.to_timedelta(df_activity_log["Time"], errors='coerce').dt.total_seconds() / 3600

зустрічається формат MM:SS.f - треба обробити:

In [49]:
def time_to_hours(t):
    if pd.isna(t):
        return None
    t = str(t)
    parts = t.split(":")
    if len(parts) == 3:
        # H:MM:SS
        return int(parts[0]) + int(parts[1]) / 60 + float(parts[2]) / 3600
    elif len(parts) == 2:
        # MM:SS.f
        return float(parts[0]) / 60 + float(parts[1]) / 3600
    return None

df_activity_log["Time_hours"] = df_activity_log["Time"].apply(time_to_hours)

In [50]:
# Перевірка аномалій df_activity:

df_activity_log["speed_kmh"] = df_activity_log["Distance"] / df_activity_log["Time_hours"]

df_activity_log[["Distance", "Time", "Time_hours", "speed_kmh"]].head(10)

   Distance     Time  Time_hours  speed_kmh
0      6.00  0:43:55    0.731944   8.197343
1      6.50  0:47:04    0.784444   8.286119
2      5.01  0:40:29    0.674722   7.425278
3      7.01  0:52:55    0.881944   7.948346
4      5.19  0:41:35    0.693056   7.488577
5      6.51  0:45:48    0.763333   8.528384
6      5.01  0:35:11    0.586389   8.543818
7      5.00  0:35:29    0.591389   8.454674
8      6.00  0:42:31    0.708611   8.467268
9      3.11  0:25:04    0.417778   7.444149

In [51]:

anomalies_activity_log = df_activity_log[df_activity_log["speed_kmh"] > 20][["Title", "Distance", "Time", "speed_kmh"]]
anomalies_activity_log.head(10)

Empty DataFrame
Columns: [Title, Distance, Time, speed_kmh]
Index: []

В df_activity відсутня колонка "Steps" на основі якої ми вище обраховували normal_steps_per_km для надійної перевірки аномальності. Тому тут покладаємось лище на speed_kmh. І така перевірка показала що аномальних активностей в четвертому датасеті немає.

Ми завершили перевірку на аномальність і видалили усі підозрілі записи з 4 датасетів.
___

### КОНВЕРТАЦІЯ ДАНИХ

Date в усіх датасетах — це (object) і для часового аналізу треба її конвертувати в datetime

In [52]:
df_personal["Date"] = pd.to_datetime(df_personal["Date"])

df_partner["Date"] = pd.to_datetime(df_partner["Date"])

df_activity_bob["Date"] = pd.to_datetime(df_activity_bob["Date"])

df_activity_log["Date"] = pd.to_datetime(df_activity_log["Date"], format="mixed")

In [53]:
print(df_personal["Date"].head())
print(df_partner["Date"].head())
print(df_activity_bob["Date"].head())
print(df_activity_log["Date"].head())

0   2026-05-17 11:56:00
1   2026-05-16 14:20:24
2   2026-05-09 11:45:01
3   2026-05-03 10:16:03
4   2026-05-02 12:04:59
Name: Date, dtype: datetime64[ns]
0   2026-04-19 12:30:22
1   2026-04-19 11:45:37
2   2026-04-18 13:15:35
3   2026-04-14 16:56:03
4   2026-04-14 16:05:04
Name: Date, dtype: datetime64[ns]
0   2026-05-19 07:15:28
1   2026-05-16 10:30:56
2   2026-05-10 08:18:24
3   2026-05-09 06:22:41
4   2026-05-07 06:00:01
Name: Date, dtype: datetime64[ns]
0   2020-07-15 09:41:00
1   2020-07-14 17:45:00
2   2020-07-13 18:57:00
3   2020-07-12 18:44:00
4   2020-07-11 19:35:00
Name: Date, dtype: datetime64[ns]

Avg Pace та Best Pace слід конвертувати в число:

In [54]:
print(df_personal["Avg Pace"].head())
print(df_partner["Avg Pace"].head())
print(df_activity_bob["Avg Pace"].head())
print(df_activity_log["Avg Pace"].head())

0     7:58
1    11:24
2    13:54
3    11:01
4    10:07
Name: Avg Pace, dtype: object
0     9:47
1     8:25
2     7:24
3    14:49
4    10:33
Name: Avg Pace, dtype: object
0    11:51
1    11:52
2    10:26
3    10:49
4    10:50
Name: Avg Pace, dtype: object
0    7:19
1    7:14
2    8:05
3    7:33
4    8:01
Name: Avg Pace, dtype: object

In [55]:
def pace_to_float(pace_str):
    if pd.isna(pace_str) or pace_str is None:
        return None
    pace_str = str(pace_str).replace(',', '.')  # замінюємо кому на крапку
    if ":" in str(pace_str):
        parts = str(pace_str).split(":")
        return int(parts[0]) + int(parts[1]) / 60
    else:
        return float(pace_str)


df_personal["Avg Pace num"] = df_personal["Avg Pace"].apply(pace_to_float)

df_personal["Best Pace num"] = df_personal["Best Pace"].apply(pace_to_float)

print(df_personal["Avg Pace num"].head())
print(df_personal["Best Pace num"].head())

0     7.966667
1    11.400000
2    13.900000
3    11.016667
4    10.116667
Name: Avg Pace num, dtype: float64
0    5.233333
1    5.066667
2    4.633333
3    4.550000
4    4.316667
Name: Best Pace num, dtype: float64

In [56]:
df_partner["Avg Pace num"] = df_partner["Avg Pace"].apply(pace_to_float)

df_partner["Best Pace num"] = df_partner["Best Pace"].apply(pace_to_float)

print(df_partner["Avg Pace num"].head())
print(df_partner["Best Pace num"].head())

0     9.783333
1     8.416667
2     7.400000
3    14.816667
4    10.550000
Name: Avg Pace num, dtype: float64
0    4.683333
1    5.000000
2    4.366667
3    6.633333
4    4.550000
Name: Best Pace num, dtype: float64

In [57]:
df_activity_bob["Avg Pace num"] = df_activity_bob["Avg Pace"].apply(pace_to_float)

df_activity_bob["Best Pace num"] = df_activity_bob["Best Pace"].apply(pace_to_float)

print(df_activity_bob["Avg Pace num"].head())
print(df_activity_bob["Best Pace num"].head())

0    11.850000
1    11.866667
2    10.433333
3    10.816667
4    10.833333
Name: Avg Pace num, dtype: float64
0    6.816667
1    7.033333
2    6.133333
3    6.583333
4    6.516667
Name: Best Pace num, dtype: float64

In [58]:
df_activity_log["Avg Pace num"] = df_activity_log["Avg Pace"].apply(pace_to_float)

df_activity_log["Best Pace num"] = df_activity_log["Best Pace"].apply(pace_to_float)

print(df_activity_log["Avg Pace num"].head())
print(df_activity_log["Best Pace num"].head())

0    7.316667
1    7.233333
2    8.083333
3    7.550000
4    8.016667
Name: Avg Pace num, dtype: float64
0    6.333333
1    6.583333
2    5.816667
3    5.000000
4    6.800000
Name: Best Pace num, dtype: float64

In [59]:
# перевірка

df_personal[["Avg Pace", "Avg Pace num", "Best Pace", "Best Pace num"]].head()

  Avg Pace  Avg Pace num Best Pace  Best Pace num
0     7:58      7.966667      5:14       5.233333
1    11:24     11.400000      5:04       5.066667
2    13:54     13.900000      4:38       4.633333
3    11:01     11.016667      4:33       4.550000
4    10:07     10.116667      4:19       4.316667

___

### УНІФІКАЦІЯ НАЗВ КОЛОНОК

В df_activity маємо колонки Elev Gain і Elev Loss замість Total Ascent і Total Descent як в двох інших датасетах. Перейменовуємо:

In [60]:
df_activity_log = df_activity_log.rename(columns={"Elev Gain": "Total Ascent", "Elev Loss": "Total Descent"})

In [61]:
print(df_activity_log["Total Ascent"].head())
print(df_activity_log["Total Descent"].head())

0    169
1    183
2    124
3    215
4     76
Name: Total Ascent, dtype: object
0    173
1    187
2    124
3    219
4     80
Name: Total Descent, dtype: object

##### скористаємось errors="coerce" — якщо лишились нечислові значення він поставить NaN:

In [62]:
for df in [df_personal, df_partner, df_activity_bob, df_activity_log]:
    df["Total Ascent"] = pd.to_numeric(df["Total Ascent"], errors="coerce")
    df["Total Descent"] = pd.to_numeric(df["Total Descent"], errors="coerce")

In [63]:
for df in [df_personal, df_partner, df_activity_bob, df_activity_log]:
    df["Calories"] = pd.to_numeric(df["Calories"], errors="coerce")

___

### ОБ'ЄДНУЄМО ДАНІ АТЛЕТІВ

створюємо додаткову колонку "Athlete" для ідентифікації (маркер):

In [64]:
df_personal["Athlete"] = "fox_1"

df_partner["Athlete"] = "fox_2"

df_activity_bob["Athlete"] = "not_a_fox_1"

df_activity_log["Athlete"] = "not_a_fox_2"

комбінуємо датафрейми для подальшого аналізу:

In [65]:
df_combined = pd.concat([df_personal, df_partner, df_activity_bob, df_activity_log], ignore_index=True)

In [66]:
# перевірка

print(df_combined.shape)
print(df_combined["Athlete"].value_counts())

(1877, 47)
Athlete
not_a_fox_2    682
not_a_fox_1    624
fox_1          295
fox_2          276
Name: count, dtype: int64

Збережемо очищені дані:

In [67]:
df_combined.to_csv("../data/processed/garmin_combined.csv", index=False)

На цьому ми завершили процес знайомства з даними, їх очистку, конвертацію та об'єднаня в один датасет для подальшого аналізу
___

### EDA - > file 02_eda.ipynb